### PR TITLE
Resolves #54

### PR DESCRIPTION
**Pull request by brittwitham**

### CODE REVIEW

**Comment by gustavohandrade** [comment]
@psdcode Currently, the app is sending this request to the server under the hood when a search is launched:
https://sks-server-ajah-ttwto.ondigitalocean.app/search?q=environment&doctype=activity,entity&municipality=&operator=and&region=

We need to update that to remove '&region=' and '&municipality=' to become more like below, it should be successful 
https://sks-server-ajah-ttwto.ondigitalocean.app/search?q=environment&doctype=activity,entity&operator=and

Initially the blank region & municipality parameters were needed, but I cleaned some stuff up and we don't need them anymore.

The fix is chilling in a draft PR here: https://github.com/ajah/sks-server/pull/8, so it's ready to go once that change is made.

**Comment by psdcode** [comment]
@brittwitham ok, great, yeah, I noticed we are forced to send those over even if blank or otherwise error occurs. I will merge this in as soon at the same time as I make the relevant change to the front end

**Comment by psdcode** [comment]
@brittwitham can you resolve the conflict on here?

**Comment by psdcode** [comment]
I'm confused, this was reverted? 
Screen Shot 2022-11-11 at 01 11 13

**Comment by brittwitham** [comment]
@psdcode I reverted this to avoid it breaking on the live site before your changes were made, but in hindsight I think that was unnecessary - restoring it now!

**Pull request merged**
